AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket for CloudFormation Template

Parameters:
  BucketName:
    Description: keerthi-s3-bucket 
    Type: String
    Default: keerthi-bucket

  BucketVersioning:
    Description: Enable versioning for the S3 bucket.
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be either 'true' or 'false'.

  Environment:
    Description: Environment name tag for the S3 bucket.
    Type: String
    Default: dev

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Ref: BucketName
      VersioningConfiguration:
        Status: Enabled  